name: Build packages and push to binary cache
on:
  pull_request:
  push:

jobs:
  build-pkgs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v6

      - name: Build packages and push to cachix
        uses: cachix/cachix-action@v3
        with:
          name: gerschtli
          file: ci.nix
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}


  build-overlays-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build packages and push to cachix
        uses: uraimo/run-on-arch-action@v1.0.7
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            set -exo pipefail
            apt update
            apt install -y curl xz-utils

            adduser --disabled-password --gecos "" --uid 1001 runner

            mkdir -p /etc/nix
            echo http2 = false >> /etc/nix/nix.conf
            echo max-jobs = auto >> /etc/nix/nix.conf
            echo trusted-users = root runner >> /etc/nix/nix.conf

            mkdir -m 0755 /nix && chown runner /nix
            curl -o install.sh https://nixos.org/nix/install

            echo export HOME=/home/runner > /etc/nix/cachix-push.sh
            echo export CACHIX_SIGNING_KEY=${{ secrets.CACHIX_SIGNING_KEY }} >> /etc/nix/cachix-push.sh
            echo export PATH=\$PATH:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/per-user/runner/profile/bin >> /etc/nix/cachix-push.sh
            echo /nix/var/nix/profiles/per-user/runner/profile/bin/cachix push gerschtli \$OUT_PATHS >> /etc/nix/cachix-push.sh
            chmod +x /etc/nix/cachix-push.sh

            export CACHIX_SIGNING_KEY=${{ secrets.CACHIX_SIGNING_KEY }}

            su -c "sh install.sh
              . /home/runner/.nix-profile/etc/profile.d/nix.sh
              nix-env -iA cachix -f https://cachix.org/api/v1/install --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= --keep-going || :
              nix-env -iA cachix -f https://cachix.org/api/v1/install --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= --keep-going && cachix use gerschtli && echo post-build-hook = /etc/nix/cachix-push.sh >> /etc/nix/nix.conf || :
              nix-build ci-overlays.nix --argstr arch aarch64" runner


  build-overlays-i686:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v6

      - name: Build packages and push to cachix
        uses: cachix/cachix-action@v3
        with:
          name: gerschtli
          file: ci-overlays.nix
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
